#!/usr/bin/env python3
"""
Test script to validate the mealworm application structure
This script tests the basic structure without external dependencies
"""

import sys
import os
from datetime import datetime

# Add the current directory to the path
sys.path.insert(0, os.path.dirname(__file__))

def test_imports():
    """Test that all modules can be imported"""
    print("🧪 Testing module imports...")
    
    try:
        from mealworm.models import Meal, DayPlan, WeeklyMealPlan, MealPlanningState
        print("✅ Models imported successfully")
    except ImportError as e:
        print(f"❌ Models import failed: {e}")
        return False
    
    try:
        from mealworm.config import Config
        print("✅ Config imported successfully")
    except ImportError as e:
        print(f"❌ Config import failed: {e}")
        return False
    
    try:
        from mealworm.formatter import MealPlanFormatter
        print("✅ Formatter imported successfully")
    except ImportError as e:
        print(f"❌ Formatter import failed: {e}")
        return False
    
    # Skip workflow and notion_client as they have external dependencies
    print("⏭️ Skipping workflow and notion_client (require external dependencies)")
    
    return True

def test_models():
    """Test model creation and validation"""
    print("\n🧪 Testing model functionality...")
    
    from mealworm.models import Meal, DayPlan, WeeklyMealPlan
    
    try:
        # Create a test meal
        meal = Meal(
            id="test-1",
            title="Spaghetti Carbonara",
            description="Classic Italian pasta dish",
            cuisine_type="Italian",
            prep_time=30,
            tags=["pasta", "italian", "quick"]
        )
        print(f"✅ Created meal: {meal.title}")
        
        # Create a day plan
        day_plan = DayPlan(
            day="Sunday",
            dinner=meal
        )
        print(f"✅ Created day plan for {day_plan.day}")
        
        # Create a weekly plan
        weekly_plan = WeeklyMealPlan(
            week_starting=datetime.now(),
            days=[day_plan],
            notes="Test meal plan"
        )
        print(f"✅ Created weekly plan with {len(weekly_plan.days)} days")
        
        return weekly_plan
        
    except Exception as e:
        print(f"❌ Model test failed: {e}")
        return None

def test_formatter():
    """Test the formatter functionality"""
    print("\n🧪 Testing formatter functionality...")
    
    from mealworm.models import Meal, DayPlan, WeeklyMealPlan
    from mealworm.formatter import MealPlanFormatter
    
    try:
        # Create test data
        meals = [
            Meal(id="1", title="Spaghetti Carbonara", cuisine_type="Italian", prep_time=30),
            Meal(id="2", title="Chicken Teriyaki", cuisine_type="Japanese", prep_time=25),
            Meal(id="3", title="Beef Tacos", cuisine_type="Mexican", prep_time=20)
        ]
        
        days = [
            DayPlan(day="Sunday", dinner=meals[0]),
            DayPlan(day="Monday", dinner=meals[1]),
            DayPlan(day="Tuesday", dinner=meals[2])
        ]
        
        weekly_plan = WeeklyMealPlan(
            week_starting=datetime.now(),
            days=days,
            notes="Test meal plan generated by mealworm"
        )
        
        # Test different formats
        text_output = MealPlanFormatter.to_text(weekly_plan)
        simple_output = MealPlanFormatter.to_simple_template(weekly_plan)
        markdown_output = MealPlanFormatter.to_markdown(weekly_plan)
        
        print("✅ Text format generated")
        print("✅ Simple format generated")
        print("✅ Markdown format generated")
        
        return text_output
        
    except Exception as e:
        print(f"❌ Formatter test failed: {e}")
        return None

def test_config():
    """Test configuration"""
    print("\n🧪 Testing configuration...")
    
    from mealworm.config import Config
    
    try:
        print(f"✅ Days of week: {Config.DAYS_OF_WEEK}")
        print(f"✅ Notion MCP URL: {Config.NOTION_MCP_URL}")
        
        # Test validation (will fail without API key, but that's expected)
        try:
            Config.validate()
            print("✅ Config validation passed")
        except ValueError as e:
            print(f"⚠️ Config validation failed (expected): {e}")
        
        return True
        
    except Exception as e:
        print(f"❌ Config test failed: {e}")
        return False

def main():
    """Run all tests"""
    print("🐛 Mealworm Application Structure Test")
    print("=" * 50)
    
    success = True
    
    # Test imports
    if not test_imports():
        success = False
    
    # Test models
    weekly_plan = test_models()
    if not weekly_plan:
        success = False
    
    # Test formatter
    formatted_output = test_formatter()
    if not formatted_output:
        success = False
    else:
        print("\n📋 Sample formatted output:")
        print("-" * 30)
        print(formatted_output[:500] + "..." if len(formatted_output) > 500 else formatted_output)
    
    # Test config
    if not test_config():
        success = False
    
    print("\n" + "=" * 50)
    if success:
        print("🎉 All tests passed! The mealworm application structure is working correctly.")
        print("\n📝 Next steps:")
        print("1. Set up your OpenAI API key in .env file")
        print("2. Configure Notion MCP server access")
        print("3. Install required dependencies when available")
        print("4. Run: python main.py")
    else:
        print("❌ Some tests failed. Please check the errors above.")
        
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())