"""Add authentication tables

Revision ID: dd9e8cb112a6
Revises:
Create Date: 2026-01-04 22:39:41.064680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd9e8cb112a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)

    # Create user_preferences table
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chicken_dishes_per_week", sa.Integer(), nullable=True),
        sa.Column("fish_dishes_per_week", sa.Integer(), nullable=True),
        sa.Column("vegetables_required", sa.Boolean(), nullable=True),
        sa.Column("eating_out_days", sa.JSON(), nullable=True),
        sa.Column("leftovers_for_lunch", sa.Boolean(), nullable=True),
        sa.Column("likes", sa.JSON(), nullable=True),
        sa.Column("dislikes", sa.JSON(), nullable=True),
        sa.Column("preferred_cuisines", sa.JSON(), nullable=True),
        sa.Column("sauce_preference", sa.String(length=255), nullable=True),
        sa.Column("easy_meal_preference", sa.Text(), nullable=True),
        sa.Column("dietary_restrictions", sa.JSON(), nullable=True),
        sa.Column("allergens", sa.JSON(), nullable=True),
        sa.Column("avoid_meal_types", sa.JSON(), nullable=True),
        sa.Column("other_items", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_preferences_user_id"),
        "user_preferences",
        ["user_id"],
        unique=True,
    )

    # Create generated_meal_plans table
    op.create_table(
        "generated_meal_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("week_starting", sa.DateTime(), nullable=False),
        sa.Column("markdown_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generated_meal_plans_user_id"),
        "generated_meal_plans",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_meal_plans_week_starting"),
        "generated_meal_plans",
        ["week_starting"],
        unique=False,
    )

    # Note: Keeping old langchain tables for now to avoid breaking existing vector db functionality
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_plans",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column(
            "usage",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("content_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="meal_plans_pkey"),
    )
    op.create_index("idx_meal_plans_name", "meal_plans", ["name"], unique=False)
    op.create_index("idx_meal_plans_id", "meal_plans", ["id"], unique=False)
    op.create_index(
        "idx_meal_plans_content_id", "meal_plans", ["content_id"], unique=False
    )
    op.create_index(
        "idx_meal_plans_content_hash", "meal_plans", ["content_hash"], unique=False
    )
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("collection_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("document", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("custom_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name="langchain_pg_embedding_collection_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name="langchain_pg_embedding_pkey"),
    )
    op.create_table(
        "langchain_pg_collection",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("uuid", name="langchain_pg_collection_pkey"),
    )
    # ### end Alembic commands ###
